language: python
python:
    - "3.7"
env:
    - DJANGO=2.2
    - DJANGO=3.0
    - DJANGO=3.1
install:
    - pip install -q Django==$DJANGO
    - pip install .
script:
    # Test running as standalone script
    - python src/fish_completions/management/commands/fish_completions.py
    # Test running as management command
    - python -m django startproject testproject
    - cd testproject
    - ./manage.py startapp testapp
    - sed "s/INSTALLED_APPS = \[/INSTALLED_APPS = \['fish_completions',/" testproject/settings.py -i
    - ./manage.py fish_completions --enable
    - ./manage.py fish_completions
