# This file has been generated by the Django package fish-django-completions.
# It fetches completions for manage.py by running `manage.py fish_completions`.
eval (commandline --tokenize)[1] fish_completions | source -
